/*
====================================================================
SUPPLYVISION
Business Intelligence Queries
Author  : Amit Sharma
Database: supplyvision

Purpose:
This file contains business-focused SQL queries used for reporting,
KPI calculation, and management decision-making.

====================================================================
*/

USE supplyvision;


/*
====================================================================
Business Query 1
Total Revenue
====================================================================

Purpose:
Calculate the total revenue generated from all orders.

Business Value:
Provides an overall sales performance metric.
====================================================================
*/

SELECT
    ROUND(SUM(qty * price), 2) AS Total_Revenue
FROM order_items;

/*
====================================================================
Business Query 2
Total Orders
====================================================================

Purpose:
Calculate the total number of customer orders.

Business Value:
Measures transaction volume.
====================================================================
*/

SELECT
    COUNT(*) AS Total_Orders
FROM orders;

/*
====================================================================
Business Query 3
Average Order Value (AOV)
====================================================================

Purpose:
Calculate the average revenue generated per order.

Business Value:
Helps evaluate customer purchasing behavior.
====================================================================
*/

SELECT
ROUND(
SUM(qty * price) /
COUNT(DISTINCT order_id),
2
) AS Average_Order_Value
FROM order_items;


/*
====================================================================
Business Query 4
Top 10 Best Selling Products
====================================================================

Purpose:
Identify products generating the highest revenue.

Business Value:
Supports inventory planning and marketing decisions.
====================================================================
*/

SELECT
p.product_id,
SUM(oi.qty) AS Units_Sold,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id
ORDER BY Revenue DESC
LIMIT 10;

/*
====================================================================
Business Query 5
Monthly Revenue Trend
====================================================================

Purpose:
Analyze revenue generated every month.

Business Value:
Identifies seasonal trends and sales growth.
====================================================================
*/

SELECT
o.order_month_name,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY
o.order_month,
o.order_month_name
ORDER BY
o.order_month;


/*
====================================================================
Business Query 6
Revenue by Store
====================================================================

Purpose:
Calculate revenue generated by each store.

Business Value:
Compares store performance.
====================================================================
*/

SELECT
s.store_id,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY
s.store_id
ORDER BY Revenue DESC;


/*
====================================================================
Business Query 7
Revenue by Customer City
====================================================================

Purpose:
Analyze sales contribution from different cities.

Business Value:
Helps identify high-performing markets.
====================================================================
*/

SELECT
c.city,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY
c.city
ORDER BY Revenue DESC;


/*
====================================================================
Business Query 8
Category Performance
====================================================================

Purpose:
Calculate revenue generated by each product category.

Business Value:
Identifies the strongest product categories.
====================================================================
*/

SELECT
c.category_id,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY
c.category_id
ORDER BY Revenue DESC;


/*
====================================================================
Business Query 9
Supplier Performance
====================================================================

Purpose:
Measure revenue generated by products supplied
by each supplier.

Business Value:
Evaluates supplier contribution.
====================================================================
*/

SELECT
s.supplier_id,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM suppliers s
JOIN products p
ON s.supplier_id = p.supplier_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY
s.supplier_id
ORDER BY Revenue DESC;


/*
====================================================================
Business Query 10
Weekend vs Weekday Sales
====================================================================

Purpose:
Compare sales generated during weekdays
and weekends.

Business Value:
Supports staffing and promotional planning.
====================================================================
*/

SELECT
CASE
WHEN o.is_weekend = 1 THEN 'Weekend'
ELSE 'Weekday'
END AS Day_Type,
ROUND(SUM(oi.qty * oi.price),2) AS Revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY Day_Type;


/*===========================================================
 CATEGORY ANALYSIS
===========================================================*/

-- Query 1
-- Display all product categories
SELECT *
FROM categories;

-- Query 2
-- Count total number of categories
SELECT COUNT(*) AS total_categories
FROM categories;

/*===========================================================
 STORE ANALYSIS
===========================================================*/

-- Query 3
-- List all stores
SELECT *
FROM stores;

-- Query 4
-- Count stores by city
SELECT
    city,
    COUNT(*) AS total_stores
FROM stores
GROUP BY city
ORDER BY total_stores DESC;

/*===========================================================
 SUPPLIER ANALYSIS
===========================================================*/

-- Query 5
-- Display all suppliers
SELECT *
FROM suppliers;

-- Query 6
-- Count suppliers by country
SELECT
    country,
    COUNT(*) AS total_suppliers
FROM suppliers
GROUP BY country
ORDER BY total_suppliers DESC;

/*===========================================================
 PROMOTION ANALYSIS
===========================================================*/

-- Query 7
-- List all promotions
SELECT *
FROM promotions;

-- Query 8
-- Average promotional discount
SELECT
    ROUND(AVG(discount),2) AS average_discount
FROM promotions;

-- Query 9
-- Highest promotion discount
SELECT MAX(discount) AS highest_discount
FROM promotions;

-- Query 10
-- Lowest promotion discount
SELECT MIN(discount) AS lowest_discount
FROM promotions;

/*===========================================================
 SHIPMENT ANALYSIS
===========================================================*/

-- Query 11
-- Count shipments by status
SELECT
    status,
    COUNT(*) AS total_shipments
FROM shipments
GROUP BY status
ORDER BY total_shipments DESC;

-- Query 12
-- Total number of shipments
SELECT COUNT(*) AS total_shipments
FROM shipments;


/*===========================================================
 EMPLOYEE ANALYSIS
===========================================================*/

-- Query 13
-- Display all employees
SELECT *
FROM employees;

-- Query 14
-- Average employee salary
SELECT
    ROUND(AVG(salary),2) AS average_salary
FROM employees;

-- Query 15
-- Highest employee salary
SELECT MAX(salary) AS highest_salary
FROM employees;

-- Query 16
-- Lowest employee salary
SELECT MIN(salary) AS lowest_salary
FROM employees;

-- Query 17
-- Number of employees in each store
SELECT
    store_id,
    COUNT(*) AS total_employees
FROM employees
GROUP BY store_id
ORDER BY total_employees DESC;

/*===========================================================
 RETURN ANALYSIS
===========================================================*/

-- Query 18
-- Total number of returns
SELECT COUNT(*) AS total_returns
FROM returns;

-- Query 19
-- Total refund amount
SELECT
    ROUND(SUM(refund),2) AS total_refund
FROM returns;

-- Query 20
-- Average refund amount
SELECT
    ROUND(AVG(refund),2) AS average_refund
FROM returns;

-- Query 21
-- Highest refund issued
SELECT MAX(refund) AS highest_refund
FROM returns;

-- Query 22
-- Lowest refund issued
SELECT MIN(refund) AS lowest_refund
FROM returns;

/*
====================================================================
END OF BUSINESS QUERY FILE
====================================================================
*/